(function () {
  "use strict";
  const POLL_MS = 1500;
  const SAFE_FIELDS = new Set(["mission_id", "trace_id", "event_id", "component", "authority", "event_kind", "occurred_at", "observation_sequence", "status", "outcome", "correlation_id", "parent_id", "payload", "replay_disposition", "redacted_fields", "missing_fields"]);
  const SAFE_PAYLOAD_FIELDS = new Set(["mission_snapshot_id", "snapshot_id", "plan_revision", "revision", "maneuver_id", "command_id", "correlation_id", "transition", "action", "operation", "result", "active_state", "status", "outcome", "lifecycle", "planner", "planning_profile", "state", "source", "topic", "summary", "input_start_sequence", "input_end_sequence", "prior_summary_ids", "summary_id", "target_service", "command_kind", "event", "resume_sequence"]);
  const COMPONENTS = {
    context: "Context Coordination", belief: "Bayesian Belief Manager", "hyper-agent": "Hyper Agent", pddl: "PDDL Planner", minizinc: "MiniZinc Planner", "maneuver-control": "Maneuver Control", fsm: "FSM Runner", transport: "Transport", environment: "Environment", "mission-summary": "Mission Summary"
  };
  const VIEWS = {
    overview: { title: "Mission overview", components: null, detail: "All observed mission records are in view." },
    hyper: { title: "Hyper Agent", components: ["hyper-agent", "context", "belief"], detail: "Authority, context, and belief evidence." },
    maneuver: { title: "Maneuver Control", components: ["maneuver-control", "fsm", "transport", "environment"], detail: "Decision, execution, and feedback evidence." },
    planning: { title: "Planning", components: ["pddl", "minizinc", "hyper-agent"], detail: "Symbolic and temporal planning evidence." },
    runtime: { title: "Runtime flow", components: ["context", "belief", "fsm", "transport", "environment", "mission-summary"], detail: "Public runtime and summary evidence." }
  };
  const EDGES = {
    "context|belief": ["context", "belief"], "belief|hyper-agent": ["belief", "hyper-agent"], "hyper-agent|pddl": ["hyper-agent", "pddl"], "hyper-agent|minizinc": ["hyper-agent", "minizinc"], "pddl|maneuver-control": ["pddl", "maneuver-control"], "minizinc|maneuver-control": ["minizinc", "maneuver-control"], "maneuver-control|fsm": ["maneuver-control", "fsm"], "fsm|transport": ["fsm", "transport"], "transport|environment": ["transport", "environment"], "environment|context": ["environment", "context"], "mission-summary|hyper-agent": ["mission-summary", "hyper-agent"]
  };
  const COMPONENT_BY_TRACE = { "hyper-agent":"hyper-agent", "context-coordination":"context", "maneuver-control":"maneuver-control", "fsm-runner":"fsm", transport:"transport", "command-source":"transport", "command-target":"transport", environment:"environment", "mission-log-summarizer":"mission-summary" };
  const COMPONENT_BY_SIGNATURE = { "environment|bayesian-belief":"belief", "environment|risk.observed":"belief", "environment|belief.constraints":"belief", "environment|belief.updated":"belief" };
  const PLANNER_COMPONENTS = { pddl:"pddl", symbolic:"pddl", minizinc:"minizinc", temporal:"minizinc" };
  const PLANNER_EVENT_KINDS = new Set(["planner-selection", "planner-execution", "normalized-plan"]);
  const OBSERVED_TYPE_BY_SIGNATURE = { "transport|maneuver-feedback":"TransportEvent", "command-source|command":"Command", "transport|command-receipt":"CommandReceipt", "command-target|command-outcome":"CommandOutcome", "context-coordination|mission-snapshot":"MissionSnapshot", "environment|bayesian-belief":"BayesianBeliefSnapshot", "planner|normalized-plan":"NormalizedPlan", "fsm-runner|fsm-status":"FSMStatus", "fsm-runner|fsm-execution-record":"FSMExecutionRecord", "environment|maneuver-feedback":"ManeuverFeedback", "hyper-agent|replan-request":"ReplanRequest", "mission-log-summarizer|summary":"SummaryArtifact" };
  const DECLARED_EDGE_CLASSES = { "context|belief":["MissionSnapshot", "BayesianBeliefSnapshot"], "belief|hyper-agent":["BayesianBeliefSnapshot"], "hyper-agent|pddl":["ReplanRequest"], "hyper-agent|minizinc":["ReplanRequest"], "pddl|maneuver-control":["NormalizedPlan"], "minizinc|maneuver-control":["NormalizedPlan"], "maneuver-control|fsm":[], "fsm|transport":["FSMStatus", "FSMExecutionRecord"], "transport|environment":["TransportEvent", "Command", "CommandReceipt", "CommandOutcome"], "environment|context":["ManeuverFeedback", "BayesianBeliefSnapshot"], "mission-summary|hyper-agent":["SummaryArtifact"] };
  const state = { active:false, available:false, missions:[], missionId:"", items:[], cursor:0, playing:true, speed:1, timer:null, pollTimer:null, requestToken:0, debugToken:0, selectionId:"", correlationId:"", view:"overview", inspection:null, debug:{ enabled:false, profiles:[], conversations:[] } };
  const $ = (id) => document.getElementById(id);
  const els = { runtime:$("runtimeState"), runtimeLabel:$("runtimeLabel"), session:$("sessionMeta"), picker:$("missionPicker"), mission:$("missionSelect"), count:$("observationCount"), graph:$("graphStage"), idle:$("idleNote"), mobileFlow:$("mobileFlow"), replay:$("replayControls"), scrubber:$("scrubber"), end:$("scrubberEnd"), play:$("playPause"), speed:$("speed"), trace:$("traceStrip"), events:$("eventList"), title:$("viewTitle"), kicker:$("inspectorKicker"), inspectorTitle:$("inspectorTitle"), inspectorCopy:$("inspectorCopy"), details:$("detailList"), body:$("inspectorBody"), safety:$("safetyList"), clear:$("clearSelection"), summaries:$("summaries"), summaryStatus:$("summaryStatus"), summaryLatest:$("summaryLatest"), summaryHistory:$("summaryHistory") };
  const text = (value, fallback = "", limit = 240) => typeof value === "string" && value.trim() ? value.trim().slice(0, limit) : fallback;
  const own = (value, key) => Object.prototype.hasOwnProperty.call(value, key);
  const json = (value) => { try { return typeof value === "string" ? value : JSON.stringify(value, null, 2); } catch (_) { return String(value); } };
  function safePayload(value) { return value && typeof value === "object" && !Array.isArray(value) ? Object.entries(value).filter(([key, item]) => SAFE_PAYLOAD_FIELDS.has(key) && ["string", "number", "boolean"].includes(typeof item)).slice(0, 7).map(([key, item]) => [key, String(item).slice(0, 160)]) : []; }
  function summaryData(value) { if (!value || typeof value !== "object" || Array.isArray(value) || !text(value.summary)) return null; return { summary:text(value.summary, "", 480), start:own(value, "input_start_sequence") ? String(value.input_start_sequence).slice(0, 40) : "", end:own(value, "input_end_sequence") ? String(value.input_end_sequence).slice(0, 40) : "", prior:Array.isArray(value.prior_summary_ids) ? value.prior_summary_ids.filter((id) => typeof id === "string").slice(0, 8) : [] }; }
  function normalize(raw, index) { if (!raw || typeof raw !== "object") return null; const item = {}; Object.keys(raw).forEach((key) => { if (SAFE_FIELDS.has(key)) item[key] = raw[key]; }); const eventId = text(item.event_id, "", 160), traceId = text(item.trace_id, eventId, 160); if (!eventId && !traceId) return null; return { key:traceId || eventId, missionId:text(item.mission_id, "unknown", 160), eventId, traceId, component:text(item.component, "runtime", 100).toLowerCase(), kind:text(item.event_kind, "observation", 120), authority:text(item.authority, "unavailable", 100), occurred:text(item.occurred_at, "time unavailable", 160), sequence:Number.isFinite(item.observation_sequence) ? item.observation_sequence : index + 1, status:text(item.status, "", 80), outcome:text(item.outcome, "", 80), correlationId:text(item.correlation_id, "", 160), parentId:text(item.parent_id, "", 160), replay:text(item.replay_disposition, "normal", 80), payload:safePayload(item.payload), summary:summaryData(item.payload), redacted:Array.isArray(item.redacted_fields) ? item.redacted_fields.filter((v) => typeof v === "string").slice(0, 12) : [], missing:Array.isArray(item.missing_fields) ? item.missing_fields.filter((v) => typeof v === "string").slice(0, 12) : [] }; }
  function feedbackIdentity(item) { if (item.kind !== "maneuver-feedback") return ""; const id = item.eventId || item.traceId; return id.startsWith("feedback:") ? id.slice("feedback:".length) : id; }
  function coalesceFeedback(items) { const byFeedback = new Map(); return items.reduce((display, item) => { const identity = feedbackIdentity(item); if (!identity) { display.push(item); return display; } const key = item.missionId + "|" + identity, existingIndex = byFeedback.get(key); if (existingIndex === undefined) { byFeedback.set(key, display.length); display.push(item); return display; } const existing = display[existingIndex]; if (item.eventId === "feedback:" + identity && existing.eventId !== "feedback:" + identity) display[existingIndex] = item; return display; }, []); }
  function signatureFor(item) { return item.component + "|" + item.kind; }
  function payloadValue(item, key) { const pair = item.payload.find(([name]) => name === key); return pair ? pair[1] : ""; }
  function componentFor(item) { const signature = signatureFor(item), mapped = COMPONENT_BY_SIGNATURE[signature] || COMPONENT_BY_TRACE[item.component]; if (mapped) return mapped; if (item.component === "planner" && PLANNER_EVENT_KINDS.has(item.kind)) return PLANNER_COMPONENTS[payloadValue(item, "planner")] || "unclassified"; return "unclassified"; }
  function edgeFor(item, items) { const child = componentFor(item); const parent = items.find((entry) => item.parentId && (entry.eventId === item.parentId || entry.traceId === item.parentId)); if (!parent) return ""; const key = componentFor(parent) + "|" + child; return EDGES[key] ? key : ""; }
  function labelForEdge(key) { const endpoints = EDGES[key]; return endpoints ? COMPONENTS[endpoints[0]] + " → " + COMPONENTS[endpoints[1]] : key; }
  function classFor(item) { const type = OBSERVED_TYPE_BY_SIGNATURE[signatureFor(item)]; return type ? type + " · " + item.kind : item.kind; }
  function componentLabel(item) { const component = componentFor(item); return COMPONENTS[component] || "Unclassified component: " + item.component; }
  function normalizeProfile(raw) { if (!raw || typeof raw !== "object") return null; const skills = Array.isArray(raw.skills) ? raw.skills.map((skill) => skill && typeof skill === "object" ? { name:text(skill.name, "Unnamed skill", 120), version:text(skill.version, "", 80), path:text(skill.path, "", 240) } : null).filter(Boolean) : []; const tools = Array.isArray(raw.tools) ? raw.tools.filter((tool) => typeof tool === "string").map((tool) => text(tool, "", 160)).filter(Boolean) : []; return { scope:text(raw.role, text(raw.agent_role, "", 120), 120), role:text(raw.agent_role, "Unassigned role", 120), skills, tools }; }
  function normalizeConversation(raw, index) { if (!raw || typeof raw !== "object") return null; const reasoning = [raw.reasoning, raw.reasoning_content, raw.reasoning_details].filter((value) => value !== null && value !== undefined); return { role:text(raw.role, "Unassigned role", 120), sequence:Number.isFinite(raw.sequence) ? raw.sequence : index + 1, input:raw.input === undefined ? raw.request : raw.input, reasoning, output:raw.output === undefined ? { content:raw.content, function_call:raw.function_call, tool_calls:raw.tool_calls } : raw.output, status:raw.status_code, finish:text(raw.finish_reason, "", 80) }; }
  function selectedItem() { return state.items.find((item) => item.key === state.selectionId) || null; }
  function matchesView(item) { const scope = VIEWS[state.view].components; return !scope || scope.includes(componentFor(item)); }
  function derive() { const cursor = Math.max(0, Math.min(state.cursor, Math.max(0, state.items.length - 1))); const live = state.available ? state.items.slice(0, cursor + 1) : []; const selected = selectedItem(); return { cursor, live, viewItems:live.filter(matchesView), selected:selected && live.some((item) => item.key === selected.key) ? selected : null, totalInView:state.items.filter(matchesView).length }; }
  function addDetail(label, value) { const row = document.createElement("div"), dt = document.createElement("dt"), dd = document.createElement("dd"); dt.textContent = label; dd.textContent = String(value); row.append(dt, dd); els.details.append(row); }
  function clearTimer() { if (state.timer) { clearInterval(state.timer); state.timer = null; } }
  function resetTimer() { clearTimer(); if (state.available && state.playing) state.timer = setInterval(() => { if (state.items.length > 1) { state.cursor = state.cursor >= state.items.length - 1 ? 0 : state.cursor + 1; renderAll(); } }, 1000 / state.speed); }
  function resetMission(missionId) { state.requestToken++; state.debugToken++; state.missionId = missionId; state.items = []; state.cursor = 0; state.selectionId = ""; state.correlationId = ""; state.inspection = null; state.debug = { enabled:false, profiles:[], conversations:[] }; state.playing = true; clearTimer(); }
  function renderPicker() { els.picker.hidden = !state.available || !state.missions.length; els.mission.replaceChildren(); state.missions.forEach((mission) => { const option = document.createElement("option"); option.value = mission; option.textContent = mission.slice(0, 80); option.selected = mission === state.missionId; els.mission.append(option); }); }
  function renderStatus(runtime, unavailable) { const legacy = runtime && !own(runtime, "available") && Boolean(runtime.active); state.available = Boolean(runtime && (runtime.available || legacy)) && !unavailable; state.active = state.available && Boolean(runtime && runtime.active); els.runtime.className = "runtime-state" + (unavailable ? " unavailable" : state.active ? " live" : ""); els.runtimeLabel.textContent = unavailable ? "Runtime unavailable" : state.active ? "Runtime active" : state.available ? "Runtime available" : "Runtime idle"; if (state.available && Array.isArray(runtime.mission_ids)) state.missions = runtime.mission_ids.filter((id) => typeof id === "string" && id.trim()).map((id) => id.slice(0, 160)); if (state.available && !state.missionId && state.missions.length) resetMission(state.missions[0]); els.session.textContent = state.missionId ? "Mission " + state.missionId.slice(0, 34) : ""; els.graph.classList.toggle("live", state.active); els.idle.hidden = state.available; els.replay.hidden = !state.available; els.trace.hidden = !state.available; renderPicker(); }
  function related(item, selected) { return selected && (item.key === selected.key || (selected.correlationId && item.correlationId === selected.correlationId) || (selected.eventId && item.parentId === selected.eventId) || (selected.traceId && item.parentId === selected.traceId)); }
  function renderGraph(model) { document.querySelectorAll(".node").forEach((node) => node.classList.remove("focused", "view-muted", "view-focus", "selected")); document.querySelectorAll(".edge").forEach((edge) => edge.classList.remove("active-flow", "related", "selected")); els.mobileFlow.replaceChildren(); if (!state.available) { els.count.textContent = "Architecture ready"; return; } els.count.textContent = state.view === "overview" ? state.items.length + " observed" : model.totalInView + " in view / " + state.items.length + " observed"; const scope = VIEWS[state.view].components; const activeEdges = new Set(); model.viewItems.forEach((item) => { const component = componentFor(item), node = document.querySelector('.node[data-component="' + component + '"]'); if (node) node.classList.add("focused"); const edge = edgeFor(item, model.live); if (edge) activeEdges.add(edge); }); if (scope) document.querySelectorAll(".node").forEach((node) => node.classList.add(scope.includes(node.dataset.component) ? "view-focus" : "view-muted")); activeEdges.forEach((key) => { const edge = document.querySelector('.edge[data-edge="' + key + '"]'); if (edge) edge.classList.add("active-flow"); const chip = document.createElement("button"); chip.type = "button"; chip.className = "flow-chip"; chip.dataset.edge = key; chip.textContent = labelForEdge(key); els.mobileFlow.append(chip); }); if (model.selected) model.live.filter((item) => related(item, model.selected)).forEach((item) => { const edge = edgeFor(item, model.live); const element = edge && document.querySelector('.edge[data-edge="' + edge + '"]'); if (element) element.classList.add("related"); }); if (state.inspection) { const selector = state.inspection.type === "component" ? '.node[data-component="' + state.inspection.id + '"]' : '.edge[data-edge="' + state.inspection.id + '"]'; const element = document.querySelector(selector); if (element) element.classList.add("selected"); } }
  function renderEvents(model) { els.events.replaceChildren(); model.viewItems.forEach((item) => { const button = document.createElement("button"), seq = document.createElement("span"), kind = document.createElement("strong"), meta = document.createElement("small"), selected = Boolean(model.selected && item.key === model.selected.key); button.type = "button"; button.className = "event" + (selected ? " selected" : "") + (related(item, model.selected) ? " related" : ""); button.dataset.key = item.key; button.setAttribute("aria-label", "Inspect observed event " + item.sequence + ": " + item.kind); button.setAttribute("aria-pressed", String(selected)); seq.className = "sequence"; seq.textContent = "OBS " + item.sequence; kind.textContent = item.kind; meta.textContent = componentLabel(item); button.append(seq, kind, meta); els.events.append(button); }); }
  function renderSummaries(model) { const summaries = model.live.filter((item) => componentFor(item) === "mission-summary" && item.summary); els.summaries.hidden = !state.available || state.view !== "overview"; els.summaryLatest.replaceChildren(); els.summaryHistory.replaceChildren(); if (els.summaries.hidden) return; if (!summaries.length) { els.summaryStatus.textContent = "Unavailable"; els.summaryLatest.textContent = "No public summary has been observed for this mission."; return; } const latest = summaries[summaries.length - 1]; els.summaryStatus.textContent = summaries.length + " observed"; els.summaryLatest.textContent = latest.summary.summary; summaries.slice(0, -1).reverse().slice(0, 8).forEach((item) => { const button = document.createElement("button"), selected = Boolean(model.selected && item.key === model.selected.key); button.type = "button"; button.className = "summary-item" + (selected ? " selected" : ""); button.dataset.key = item.key; button.setAttribute("aria-pressed", String(selected)); button.textContent = "OBS " + item.sequence; els.summaryHistory.append(button); }); }
  function appendEmpty(message) { const empty = document.createElement("p"); empty.className = "empty-state"; empty.textContent = message; els.body.append(empty); }
  function appendEvidence(title, items) { const group = document.createElement("section"); group.className = "history-group"; const heading = document.createElement("h3"); heading.textContent = title; group.append(heading); if (!items.length) { const empty = document.createElement("p"); empty.className = "empty-state"; empty.textContent = "No observed history."; group.append(empty); } else items.slice(-24).reverse().forEach((item) => { const row = document.createElement("div"), button = document.createElement("button"), meta = document.createElement("small"); row.className = "evidence-row"; button.type = "button"; button.dataset.key = item.key; button.textContent = classFor(item); meta.textContent = "OBS " + item.sequence + " · " + item.occurred; row.append(button, meta); group.append(row); }); els.body.append(group); }
  function appendDeclaredClasses(edge) { const group = document.createElement("section"), heading = document.createElement("h3"), classes = DECLARED_EDGE_CLASSES[edge] || []; group.className = "history-group"; heading.textContent = "Declared contract classes"; group.append(heading); const detail = document.createElement("p"); detail.className = "empty-state"; detail.textContent = classes.length ? classes.join(" · ") : "No declared trace class for this connection."; group.append(detail); els.body.append(group); }
  function profileFor(component) { const role = component === "hyper-agent" ? "hyper-agent" : component === "maneuver-control" ? "maneuver-control" : ""; return role ? state.debug.profiles.filter((profile) => profile.scope === role || profile.role === role) : []; }
  function appendProfiles(component) { const profiles = profileFor(component), title = COMPONENTS[component]; const group = document.createElement("section"); group.className = "history-group"; const heading = document.createElement("h3"); heading.textContent = title + " API profile"; group.append(heading); if (!state.debug.enabled) { const empty = document.createElement("p"); empty.className = "empty-state"; empty.textContent = "No debug evidence is available for this mission."; group.append(empty); } else if (!profiles.length) { const empty = document.createElement("p"); empty.className = "empty-state"; empty.textContent = "No tools or skills were reported for this role."; group.append(empty); } else profiles.forEach((profile) => { const item = document.createElement("div"); item.className = "evidence-row"; item.textContent = "Tools: " + (profile.tools.join(", ") || "None reported") + "\nSkills: " + (profile.skills.map((skill) => skill.name + (skill.version ? " " + skill.version : "")).join(", ") || "None reported"); item.style.whiteSpace = "pre-wrap"; group.append(item); }); els.body.append(group); }
  function appendConversations(component) { const role = component === "hyper-agent" ? "hyper-agent" : "maneuver-control"; const conversations = state.debug.conversations.filter((conversation) => conversation.role === role).sort((a, b) => a.role.localeCompare(b.role) || a.sequence - b.sequence); const group = document.createElement("section"); group.className = "history-group"; const heading = document.createElement("h3"); heading.textContent = "Conversation inspector"; group.append(heading); const list = document.createElement("div"); list.className = "conversation-list"; if (!state.debug.enabled || !conversations.length) { const empty = document.createElement("p"); empty.className = "empty-state"; empty.textContent = "No debug conversation evidence is available for this role."; list.append(empty); } else conversations.forEach((conversation) => { const card = document.createElement("article"); card.className = "conversation"; const header = document.createElement("div"); header.className = "conversation-header"; header.textContent = conversation.role + " · sequence " + conversation.sequence; card.append(header); [["Input / request", conversation.input, "input"], ["Provider reasoning", conversation.reasoning.length ? conversation.reasoning : null, "reasoning"], ["Output / content / tool calls", conversation.output, "output"]].forEach(([label, value, className]) => { const exchange = document.createElement("section"); exchange.className = "exchange " + className; const name = document.createElement("strong"), pre = document.createElement("pre"); name.textContent = label; pre.textContent = value === null || value === undefined ? "Not reported" : json(value); exchange.append(name, pre); card.append(exchange); }); list.append(card); }); group.append(list); els.body.append(group); }
  function renderInspector(model) { els.details.replaceChildren(); els.body.replaceChildren(); els.safety.replaceChildren(); const inspected = state.inspection; if (!state.available) { els.kicker.textContent = "Architecture inspector"; els.inspectorTitle.textContent = "Select a component or flow"; els.inspectorCopy.textContent = "No available mission is selected."; return; } if (inspected && inspected.type === "edge") { const evidence = model.live.filter((item) => edgeFor(item, model.live) === inspected.id); els.kicker.textContent = "Directed flow"; els.inspectorTitle.textContent = labelForEdge(inspected.id); els.inspectorCopy.textContent = evidence.length ? "Observed evidence traversing this flow." : "No observed evidence traverses this flow in the replay window."; addDetail("Observed evidence", evidence.length); appendEvidence("Observed traversal evidence", evidence); appendDeclaredClasses(inspected.id); return; } if (inspected && inspected.type === "component") { const component = inspected.id, output = model.live.filter((item) => componentFor(item) === component && edgeFor(item, model.live).startsWith(component + "|")), input = model.live.filter((item) => { const edge = edgeFor(item, model.live); return edge && EDGES[edge][1] === component; }); els.kicker.textContent = "Component history"; els.inspectorTitle.textContent = COMPONENTS[component]; els.inspectorCopy.textContent = "Durable observed input and output evidence."; addDetail("Observed", output.length + input.length); if (component === "pddl" || component === "minizinc") addDetail("Planning", component === "pddl" ? "Symbolic evidence only" : "Temporal evidence only"); appendEvidence("Input history", input); appendEvidence("Output history", output); if (component === "hyper-agent" || component === "maneuver-control") { appendProfiles(component); appendConversations(component); } return; } const item = model.selected; if (!item) { els.kicker.textContent = VIEWS[state.view].title; els.inspectorTitle.textContent = VIEWS[state.view].title; els.inspectorCopy.textContent = VIEWS[state.view].detail; return; } els.kicker.textContent = "Observed event " + item.sequence; els.inspectorTitle.textContent = item.kind; els.inspectorCopy.textContent = componentLabel(item) + " reported this observation."; [["Component", item.component], ["Authority", item.authority], ["Occurred", item.occurred], ["Event ID", item.eventId || item.traceId], ["Correlation", item.correlationId || "not reported"], ["Replay", item.replay]].forEach(([label, value]) => addDetail(label, value)); item.payload.forEach(([label, value]) => addDetail(label, value)); item.redacted.forEach((field) => { const note = document.createElement("p"); note.className = "safety-note"; note.textContent = "Redacted: " + field; els.safety.append(note); }); item.missing.forEach((field) => { const note = document.createElement("p"); note.className = "safety-note red"; note.textContent = "Missing: " + field; els.safety.append(note); }); }
  function renderReplay(model) { els.scrubber.max = Math.max(0, state.items.length - 1); els.scrubber.value = model.cursor; els.end.textContent = state.items.length + " observed"; els.play.textContent = state.playing ? "Pause" : "Play"; els.clear.hidden = !state.correlationId; }
  function renderAll() { const model = derive(); state.cursor = model.cursor; renderGraph(model); renderEvents(model); renderSummaries(model); renderInspector(model); renderReplay(model); }
  async function loadTrace() { const missionId = state.missionId, token = ++state.requestToken; if (!missionId) return; const response = await fetch("/api/trace?mission_id=" + encodeURIComponent(missionId), { headers:{ Accept:"application/json" }, cache:"no-store" }); if (!response.ok) throw new Error("trace unavailable"); const trace = await response.json(); if (token === state.requestToken && missionId === state.missionId && state.available) { const normalized = Array.isArray(trace.items) ? trace.items.map(normalize).filter((item) => item && item.missionId === missionId) : []; state.items = coalesceFeedback(normalized); state.cursor = Math.min(state.cursor, Math.max(0, state.items.length - 1)); } }
  async function loadDebug() { const missionId = state.missionId, token = ++state.debugToken; if (!missionId) return; try { const response = await fetch("/api/debug?mission_id=" + encodeURIComponent(missionId), { headers:{ Accept:"application/json" }, cache:"no-store" }); if (!response.ok) throw new Error("debug unavailable"); const debug = await response.json(); if (token === state.debugToken && missionId === state.missionId && state.available) state.debug = { enabled:Boolean(debug && debug.enabled), profiles:Array.isArray(debug && debug.profiles) ? debug.profiles.map(normalizeProfile).filter(Boolean) : [], conversations:Array.isArray(debug && debug.conversations) ? debug.conversations.map(normalizeConversation).filter(Boolean).sort((a, b) => a.role.localeCompare(b.role) || a.sequence - b.sequence) : [] }; } catch (_) { if (token === state.debugToken) state.debug = { enabled:false, profiles:[], conversations:[] }; } }
  async function refreshMission() { if (!state.available) return; try { await Promise.all([loadTrace(), loadDebug()]); } catch (_) { state.items = []; } renderAll(); resetTimer(); }
  async function poll() { try { const response = await fetch("/api/runtime", { headers:{ Accept:"application/json" }, cache:"no-store" }); if (!response.ok) throw new Error("runtime unavailable"); renderStatus(await response.json(), false); await refreshMission(); } catch (_) { renderStatus(null, true); renderAll(); clearTimer(); } if (state.active) state.pollTimer = setTimeout(poll, POLL_MS); }
  function inspectEvent(item) { state.selectionId = item.key; state.correlationId = item.correlationId || item.eventId || item.traceId; state.inspection = null; state.cursor = Math.max(state.cursor, state.items.findIndex((entry) => entry.key === item.key)); renderAll(); }
  document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { state.view = tab.dataset.view; state.inspection = null; document.querySelectorAll(".tab").forEach((button) => { const active = button === tab; button.classList.toggle("active", active); button.setAttribute("aria-selected", String(active)); }); els.title.textContent = VIEWS[state.view].title; renderAll(); }));
  els.mission.addEventListener("change", () => { if (state.missions.includes(els.mission.value)) { resetMission(els.mission.value); renderPicker(); renderAll(); refreshMission(); } }); $("playPause").addEventListener("click", () => { state.playing = !state.playing; renderAll(); resetTimer(); }); $("restart").addEventListener("click", () => { state.cursor = 0; state.playing = true; renderAll(); resetTimer(); }); els.speed.addEventListener("change", () => { state.speed = Number(els.speed.value); resetTimer(); }); els.scrubber.addEventListener("input", () => { state.cursor = Number(els.scrubber.value); state.playing = false; renderAll(); resetTimer(); });
  els.events.addEventListener("click", (event) => { const target = event.target.closest(".event"), item = target && state.items.find((entry) => entry.key === target.dataset.key); if (item) inspectEvent(item); }); els.summaryHistory.addEventListener("click", (event) => { const target = event.target.closest(".summary-item"), item = target && state.items.find((entry) => entry.key === target.dataset.key); if (item) inspectEvent(item); }); els.body.addEventListener("click", (event) => { const target = event.target.closest("button[data-key]"), item = target && state.items.find((entry) => entry.key === target.dataset.key); if (item) inspectEvent(item); }); els.clear.addEventListener("click", () => { state.correlationId = ""; renderAll(); }); document.querySelectorAll(".node").forEach((node) => node.addEventListener("click", () => { state.inspection = { type:"component", id:node.dataset.component }; renderAll(); })); document.querySelectorAll(".edge").forEach((edge) => edge.addEventListener("click", () => { state.inspection = { type:"edge", id:edge.dataset.edge }; renderAll(); })); els.mobileFlow.addEventListener("click", (event) => { const button = event.target.closest("button[data-edge]"); if (button) { state.inspection = { type:"edge", id:button.dataset.edge }; renderAll(); } });
  renderAll(); poll();
}());
