(function () {
  "use strict";

  const POLL_MS = 1500;
  const SAFE_FIELDS = new Set(["mission_id", "trace_id", "event_id", "component", "authority", "event_kind", "occurred_at", "observation_sequence", "source_sequence", "status", "outcome", "correlation_id", "parent_id", "payload", "replay_disposition", "redacted_fields", "missing_fields"]);
  const SAFE_PAYLOAD_FIELDS = new Set(["mission_snapshot_id", "snapshot_id", "plan_revision", "revision", "maneuver_id", "command_id", "correlation_id", "transition", "action", "operation", "result", "active_state", "status", "outcome", "lifecycle", "planner", "planning_profile", "state", "source", "topic", "source_health", "source_freshness", "freshness", "health", "input_summary", "input_min", "input_max", "input_range", "summary", "input_start_sequence", "input_end_sequence", "prior_summary_ids", "summary_id", "prior_id", "prior_snapshot_id", "prior_summary_id", "target_service", "command_kind", "event", "resume_sequence"]);
  const VIEWS = {
    overview: { title: "Mission overview", components: null, detail: "All observed mission records are in view." },
    hyper: { title: "Hyper Agent", components: ["hyper-agent", "context"], detail: "Mission authority and coordinated public context." },
    maneuver: { title: "Maneuver Control", components: ["maneuver-control", "fsm"], detail: "Decision and transition evidence for maneuver control." },
    snapshot: { title: "Snapshot & FSM", components: ["snapshot", "context", "fsm"], detail: "Snapshot publication, coordinated context, and state-machine evidence." },
    skills: { title: "Skills & advisory", components: ["skills"], detail: "Observed advisory context only." },
    command: { title: "Command & outcome", components: ["command"], detail: "Command and outcome observations." },
    feedback: { title: "Feedback paths", components: ["feedback"], detail: "Environment lifecycle and feedback evidence." }
  };
  const DEFAULT_EDGES = { "hyper-agent": ["context|hyper"], context: ["context|snapshot"], snapshot: ["fsm|snapshot"], fsm: ["fsm|maneuver"], "maneuver-control": ["hyper|maneuver"], skills: ["hyper|skills"], command: ["command|maneuver"], feedback: ["command|feedback", "feedback|maneuver"] };
  const EDGE_LABELS = { "context|hyper": "Hyper Agent to Context", "context|snapshot": "Context to Snapshot", "fsm|snapshot": "Snapshot to FSM Runner", "fsm|maneuver": "FSM Runner to Maneuver", "hyper|maneuver": "Hyper Agent to Maneuver", "hyper|skills": "Hyper Agent to Skills", "command|maneuver": "Maneuver to Command", "command|feedback": "Command to Feedback", "feedback|maneuver": "Feedback to Maneuver" };
  const state = { active: false, missions: [], missionId: "", items: [], cursor: 0, playing: true, speed: 1, timer: null, requestToken: 0, selectionId: "", correlationId: "", view: "overview" };
  const $ = (id) => document.getElementById(id);
  const els = { runtime: $("runtimeState"), runtimeLabel: $("runtimeLabel"), session: $("sessionMeta"), picker: $("missionPicker"), mission: $("missionSelect"), count: $("observationCount"), graph: $("graphStage"), mobileFlow: $("mobileFlow"), summaries: $("summaries"), summaryStatus: $("summaryStatus"), summaryLatest: $("summaryLatest"), summaryHistory: $("summaryHistory"), replay: $("replayControls"), scrubber: $("scrubber"), end: $("scrubberEnd"), play: $("playPause"), speed: $("speed"), events: $("eventList"), trace: $("traceStrip"), title: $("viewTitle"), inspectorKicker: $("inspectorKicker"), inspectorTitle: $("inspectorTitle"), inspectorCopy: $("inspectorCopy"), details: $("detailList"), safety: $("safetyList"), clear: $("clearSelection") };

  function text(value, fallback, limit) { return typeof value === "string" && value.trim() ? value.trim().slice(0, limit || 240) : fallback; }
  function list(value) { return Array.isArray(value) ? value.filter((item) => typeof item === "string").map((item) => item.slice(0, 80)).slice(0, 12) : []; }
  function safePayload(value) {
    if (!value || typeof value !== "object" || Array.isArray(value)) return [];
    return Object.entries(value).filter(([key, item]) => SAFE_PAYLOAD_FIELDS.has(key) && (typeof item === "string" || typeof item === "number" || typeof item === "boolean")).slice(0, 6).map(([key, item]) => [String(key).slice(0, 48), String(item).slice(0, 120)]);
  }
  function summaryData(value) {
    if (!value || typeof value !== "object" || Array.isArray(value)) return null;
    const summary = text(value.summary, "", 480);
    if (!summary) return null;
    const start = typeof value.input_start_sequence === "number" || typeof value.input_start_sequence === "string" ? String(value.input_start_sequence).slice(0, 40) : "";
    const end = typeof value.input_end_sequence === "number" || typeof value.input_end_sequence === "string" ? String(value.input_end_sequence).slice(0, 40) : "";
    const prior = Array.isArray(value.prior_summary_ids) ? value.prior_summary_ids.filter((item) => typeof item === "string").slice(0, 8).map((item) => item.slice(0, 80)) : [];
    return { summary, start, end, prior };
  }
  function normalize(raw, index) {
    if (!raw || typeof raw !== "object") return null;
    const item = {}; Object.keys(raw).forEach((key) => { if (SAFE_FIELDS.has(key)) item[key] = raw[key]; });
    const eventId = text(item.event_id, "", 160), traceId = text(item.trace_id, eventId || "", 160);
    if (!eventId && !traceId) return null;
    return { key: traceId || eventId, missionId: text(item.mission_id, "unknown", 160), traceId, eventId, component: text(item.component, "runtime", 100).toLowerCase(), authority: text(item.authority, "unavailable", 100), kind: text(item.event_kind, "observation", 120), occurred: text(item.occurred_at, "time unavailable", 160), sequence: Number.isFinite(item.observation_sequence) ? item.observation_sequence : index + 1, sourceSequence: Number.isFinite(item.source_sequence) ? item.source_sequence : null, status: text(item.status, "", 80), outcome: text(item.outcome, "", 80), correlationId: text(item.correlation_id, "", 160), parentId: text(item.parent_id, "", 160), replay: text(item.replay_disposition, "normal", 80), payload: safePayload(item.payload), summary: summaryData(item.payload), redacted: list(item.redacted_fields), missing: list(item.missing_fields) };
  }
  function componentFor(item) { const name = item.component.replace(/[_ ]/g, "-"); if (name.includes("mission-log-summarizer") || name.includes("summarizer")) return "summary"; if (name.includes("hyper")) return "hyper-agent"; if (name.includes("maneuver") || name.includes("control")) return "maneuver-control"; if (name.includes("context")) return "context"; if (name.includes("fsm") || name.includes("runner")) return "fsm"; if (name.includes("snapshot") || name.includes("state")) return "snapshot"; if (name.includes("skill") || name.includes("advisor")) return "skills"; if (name.includes("feedback") || name.includes("environment")) return "feedback"; return "command"; }
  function edgeKey(first, second) { const names = { "hyper-agent": "hyper", "maneuver-control": "maneuver" }; return [names[first] || first, names[second] || second].sort().join("|"); }
  function edgesFor(item, items) { const parent = items.find((candidate) => candidate.eventId === item.parentId || candidate.traceId === item.parentId); const edge = parent ? edgeKey(componentFor(parent), componentFor(item)) : ""; return edge && EDGE_LABELS[edge] ? [edge] : (DEFAULT_EDGES[componentFor(item)] || []); }
  function selectedItem() { return state.items.find((item) => item.key === state.selectionId) || null; }
  function matchesView(item) { const components = VIEWS[state.view].components; return !components || components.includes(componentFor(item)); }
  function related(item, selected) { if (!selected) return false; return item.key === selected.key || (selected.correlationId && item.correlationId === selected.correlationId) || (selected.eventId && item.parentId === selected.eventId) || (selected.traceId && item.parentId === selected.traceId) || (item.eventId && selected.parentId === item.eventId) || (item.traceId && selected.parentId === item.traceId); }
  function derive() {
    const cursor = Math.max(0, Math.min(state.cursor, Math.max(state.items.length - 1, 0)));
    const live = state.active ? state.items.slice(0, cursor + 1) : [];
    const viewItems = live.filter(matchesView);
    let selected = selectedItem();
    if (selected && (!live.some((item) => item.key === selected.key) || !matchesView(selected))) selected = null;
    const correlated = selected && state.correlationId ? viewItems.filter((item) => related(item, selected)) : [];
    return { cursor, live, viewItems, selected, correlated, totalInView: state.items.filter(matchesView).length };
  }
  function resetMission(nextMission) { state.requestToken += 1; state.missionId = nextMission; state.items = []; state.cursor = 0; state.selectionId = ""; state.correlationId = ""; state.playing = true; clearTimer(); }
  function renderMissionPicker() { els.picker.hidden = !state.active || !state.missions.length; els.mission.replaceChildren(); state.missions.forEach((id) => { const option = document.createElement("option"); option.value = id; option.textContent = id.slice(0, 80); option.selected = id === state.missionId; els.mission.append(option); }); }
  function renderStatus(runtime, unavailable) {
    state.active = Boolean(runtime && runtime.active) && !unavailable;
    els.runtime.className = "runtime-state" + (unavailable ? " unavailable" : state.active ? " live" : ""); els.runtimeLabel.textContent = unavailable ? "Runtime unavailable" : state.active ? "Runtime active" : "Runtime idle";
    state.missions = state.active && Array.isArray(runtime.mission_ids) ? runtime.mission_ids.filter((id) => typeof id === "string" && id.trim()).map((id) => id.slice(0, 160)) : [];
    if (!state.active) resetMission(""); else if (!state.missions.includes(state.missionId)) resetMission(state.missions[0] || "");
    els.session.textContent = state.missionId ? "Mission " + state.missionId.slice(0, 32) : ""; els.graph.classList.toggle("live", state.active); els.replay.hidden = !state.active; els.trace.hidden = !state.active; renderMissionPicker();
  }
  function renderAll() { const model = derive(); state.cursor = model.cursor; renderGraph(model); renderSummaries(model); renderEvents(model); renderInspector(model); renderReplay(model); }
  function renderGraph(model) {
    document.querySelectorAll(".node").forEach((node) => node.classList.remove("focused", "view-muted", "view-focus")); document.querySelectorAll(".edge").forEach((edge) => edge.classList.remove("active-flow", "related")); els.mobileFlow.replaceChildren();
    if (!state.active) { els.count.textContent = "Architecture ready"; return; }
    els.count.textContent = state.view === "overview" ? state.items.length + " observed" : model.totalInView + " in view / " + state.items.length + " observed";
    const scope = VIEWS[state.view].components; if (scope) document.querySelectorAll(".node").forEach((node) => node.classList.add(scope.includes(node.dataset.component) ? "view-focus" : "view-muted"));
    const edgeIds = new Set(); model.viewItems.forEach((item) => { const node = document.querySelector('[data-component="' + componentFor(item) + '"]'); if (node) node.classList.add("focused"); edgesFor(item, model.live).forEach((id) => edgeIds.add(id)); });
    edgeIds.forEach((id) => { const edge = document.querySelector('[data-edge="' + id + '"]'); if (edge) edge.classList.add("active-flow"); const chip = document.createElement("span"); chip.className = "flow-chip active-flow"; chip.textContent = EDGE_LABELS[id]; els.mobileFlow.append(chip); });
    model.correlated.forEach((item) => edgesFor(item, model.live).forEach((id) => { const edge = document.querySelector('[data-edge="' + id + '"]'); if (edge) edge.classList.add("related"); }));
  }
  function summaryMeta(item) { const parts = []; if (item.summary.start || item.summary.end) parts.push("Input " + (item.summary.start || "?") + " to " + (item.summary.end || "?")); if (item.summary.prior.length) parts.push("Prior: " + item.summary.prior.slice(0, 4).map((id) => id.slice(0, 32)).join(", ")); return parts.join(" · "); }
  function renderSummaries(model) {
    const summaries = state.active && state.view === "overview" ? model.live.filter((item) => componentFor(item) === "summary" && item.summary) : [];
    els.summaries.hidden = !state.active || state.view !== "overview";
    els.summaryLatest.replaceChildren(); els.summaryHistory.replaceChildren();
    if (els.summaries.hidden) return;
    if (!summaries.length) { els.summaryStatus.textContent = "Unavailable"; els.summaryLatest.textContent = "No public summary has been observed for this mission."; return; }
    const latest = summaries[summaries.length - 1]; els.summaryStatus.textContent = summaries.length + " observed";
    const body = document.createElement("p"); body.textContent = latest.summary.summary; const meta = document.createElement("p"); meta.className = "summary-meta"; meta.textContent = summaryMeta(latest); els.summaryLatest.append(body, meta);
    summaries.slice(0, -1).reverse().slice(0, 8).forEach((item) => { const button = document.createElement("button"); button.type = "button"; button.className = "summary-item" + (model.selected && model.selected.key === item.key ? " selected" : ""); button.dataset.key = item.key; button.title = "Select prior summary"; button.textContent = "OBS " + item.sequence + (summaryMeta(item) ? " · " + summaryMeta(item) : ""); els.summaryHistory.append(button); });
  }
  function renderEvents(model) { els.events.replaceChildren(); if (!state.active) return; const fragment = document.createDocumentFragment(); model.viewItems.forEach((item) => { const button = document.createElement("button"); button.type = "button"; button.className = "event" + (model.selected && item.key === model.selected.key ? " selected" : "") + (model.correlated.some((entry) => entry.key === item.key) ? " related" : ""); button.dataset.key = item.key; button.setAttribute("aria-label", "Select observed event " + item.sequence + ": " + item.kind); const seq = document.createElement("span"); seq.className = "sequence"; seq.textContent = "OBS " + item.sequence; const kind = document.createElement("strong"); kind.textContent = item.kind; const meta = document.createElement("small"); meta.textContent = componentFor(item) + (item.status ? " / " + item.status : item.outcome ? " / " + item.outcome : ""); button.append(seq, kind, meta); fragment.append(button); }); els.events.append(fragment); }
  function addDetail(label, value) { const row = document.createElement("div"), dt = document.createElement("dt"), dd = document.createElement("dd"); dt.textContent = label; dd.textContent = value; row.append(dt, dd); els.details.append(row); }
  function renderInspector(model) { els.details.replaceChildren(); els.safety.replaceChildren(); const item = model.selected; if (!state.active || !item) { const view = VIEWS[state.view]; els.inspectorKicker.textContent = state.active ? view.title : "Selected event"; els.inspectorTitle.textContent = state.active ? view.title : "No observation selected"; els.inspectorCopy.textContent = state.active ? view.detail : "Trace details appear when a runtime is active and an observed event is selected."; return; } els.inspectorKicker.textContent = "Observed event " + item.sequence; els.inspectorTitle.textContent = item.kind; els.inspectorCopy.textContent = componentFor(item) + " reported this observation."; [["Mission", item.missionId], ["Event ID", item.eventId || "not reported"], ["Trace ID", item.traceId || "not reported"], ["Parent ID", item.parentId || "not reported"], ["Correlation", item.correlationId || "not reported"], ["Authority", item.authority], ["Status", item.status || item.outcome || "not reported"], ["Replay", item.replay]].forEach(([label, value]) => addDetail(label, value)); item.payload.forEach(([key, value]) => addDetail(key, value)); const notes = []; if (item.redacted.length) notes.push(["Redacted: " + item.redacted.join(", "), ""]); if (item.missing.length) notes.push(["Missing: " + item.missing.join(", "), "red"]); if (!notes.length) notes.push(["Public fields only", ""]); notes.forEach(([value, cls]) => { const note = document.createElement("p"); note.className = "safety-note " + cls; note.textContent = value; els.safety.append(note); }); }
  function renderReplay(model) { els.scrubber.max = Math.max(state.items.length - 1, 0); els.scrubber.value = model.cursor; els.end.textContent = state.items.length + " observed"; els.play.textContent = state.playing ? "Pause" : "Play"; els.play.setAttribute("aria-label", state.playing ? "Pause replay" : "Play replay"); els.clear.hidden = !state.correlationId; }
  function clearTimer() { if (state.timer) { window.clearInterval(state.timer); state.timer = null; } }
  function resetTimer() { clearTimer(); if (state.active && state.playing) state.timer = window.setInterval(() => { if (state.items.length < 2) return; state.cursor = state.cursor >= state.items.length - 1 ? 0 : state.cursor + 1; renderAll(); }, 1000 / state.speed); }
  async function loadTrace() { const missionId = state.missionId, requestToken = ++state.requestToken; if (!missionId) { state.items = []; return false; } const response = await fetch("/api/trace?mission_id=" + encodeURIComponent(missionId), { headers: { Accept: "application/json" }, cache: "no-store" }); if (requestToken !== state.requestToken || missionId !== state.missionId || !state.active) return false; if (!response.ok) throw new Error("trace unavailable"); const trace = await response.json(); if (requestToken !== state.requestToken || missionId !== state.missionId || !state.active) return false; state.items = Array.isArray(trace.items) ? trace.items.map(normalize).filter((item) => item && item.missionId === missionId) : []; state.cursor = Math.min(state.cursor, Math.max(state.items.length - 1, 0)); return true; }
  async function poll() { try { const response = await fetch("/api/runtime", { headers: { Accept: "application/json" }, cache: "no-store" }); if (!response.ok) throw new Error("runtime unavailable"); const runtime = await response.json(); renderStatus(runtime, false); if (state.active) await loadTrace(); renderAll(); resetTimer(); } catch (_) { renderStatus(null, true); renderAll(); } }
  document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { state.view = tab.dataset.view; const selected = selectedItem(); if (selected && !matchesView(selected)) { state.selectionId = ""; state.correlationId = ""; } document.querySelectorAll(".tab").forEach((button) => { const active = button === tab; button.classList.toggle("active", active); button.setAttribute("aria-selected", String(active)); }); els.title.textContent = VIEWS[state.view].title; renderAll(); }));
  els.mission.addEventListener("change", () => { if (state.missions.includes(els.mission.value)) { resetMission(els.mission.value); renderMissionPicker(); renderAll(); loadTrace().then(() => { renderAll(); resetTimer(); }).catch(() => { renderStatus(null, true); renderAll(); }); } });
  $("playPause").addEventListener("click", () => { state.playing = !state.playing; renderAll(); resetTimer(); }); $("restart").addEventListener("click", () => { state.cursor = 0; state.playing = true; renderAll(); resetTimer(); }); els.speed.addEventListener("change", () => { state.speed = Number(els.speed.value); resetTimer(); }); els.scrubber.addEventListener("input", () => { state.cursor = Number(els.scrubber.value); state.playing = false; renderAll(); resetTimer(); });
  els.events.addEventListener("click", (event) => { const target = event.target.closest(".event"); if (!target) return; const item = state.items.find((entry) => entry.key === target.dataset.key); if (!item) return; state.selectionId = item.key; state.correlationId = item.correlationId || item.eventId || item.traceId; state.cursor = Math.max(state.cursor, state.items.findIndex((entry) => entry.key === item.key)); renderAll(); }); els.clear.addEventListener("click", () => { state.correlationId = ""; renderAll(); });
  els.summaryHistory.addEventListener("click", (event) => { const target = event.target.closest(".summary-item"); if (!target) return; const item = state.items.find((entry) => entry.key === target.dataset.key); if (!item) return; state.selectionId = item.key; state.correlationId = item.correlationId || item.eventId || item.traceId; state.cursor = Math.max(state.cursor, state.items.findIndex((entry) => entry.key === item.key)); renderAll(); });
  document.querySelectorAll(".node").forEach((node) => node.addEventListener("click", () => { const item = derive().viewItems.find((entry) => componentFor(entry) === node.dataset.component); if (!item) return; state.selectionId = item.key; state.correlationId = item.correlationId || item.eventId || item.traceId; state.cursor = Math.max(state.cursor, state.items.findIndex((entry) => entry.key === item.key)); renderAll(); }));
  renderAll(); poll(); window.setInterval(poll, POLL_MS);
}());
