(function () {
  "use strict";
  const POLL_MS = 1500;
  const SAFE_FIELDS = new Set(["mission_id", "trace_id", "event_id", "component", "authority", "event_kind", "occurred_at", "observation_sequence", "source_sequence", "status", "outcome", "correlation_id", "parent_id", "payload", "replay_disposition", "redacted_fields", "missing_fields"]);
  const SAFE_PAYLOAD_FIELDS = new Set(["mission_snapshot_id", "snapshot_id", "plan_revision", "revision", "maneuver_id", "command_id", "correlation_id", "transition", "action", "operation", "result", "active_state", "status", "outcome", "lifecycle", "planner", "planning_profile", "state", "source", "topic", "source_health", "source_freshness", "freshness", "health", "input_summary", "input_min", "input_max", "input_range", "summary", "input_start_sequence", "input_end_sequence", "prior_summary_ids", "summary_id", "prior_id", "prior_snapshot_id", "prior_summary_id", "target_service", "command_kind", "event", "resume_sequence"]);
  const VIEWS = {
    overview: { title: "Mission overview", components: null, detail: "All observed mission records are in view." },
    hyper: { title: "Hyper Agent", components: ["hyper-agent", "context"], detail: "Mission authority and coordinated public context." },
    maneuver: { title: "Maneuver Control", components: ["maneuver-control", "fsm"], detail: "Decision and transition evidence for maneuver control." },
    snapshot: { title: "Snapshot & FSM", components: ["snapshot", "context", "fsm"], detail: "Snapshot publication, coordinated context, and state-machine evidence." },
    skills: { title: "Skills & advisory", components: ["skills"], detail: "Observed advisory context only." },
    command: { title: "Command & outcome", components: ["command"], detail: "Command and outcome observations." },
    feedback: { title: "Feedback paths", components: ["feedback"], detail: "Environment lifecycle and feedback evidence." },
    debug: { title: "Agent activity", components: null, detail: "Capabilities and invocation history for this mission." }
  };
  const DEFAULT_EDGES = { "hyper-agent": ["context|hyper"], context: ["context|snapshot"], snapshot: ["fsm|snapshot"], fsm: ["fsm|maneuver"], "maneuver-control": ["hyper|maneuver"], skills: ["hyper|skills"], command: ["command|maneuver"], feedback: ["command|feedback", "feedback|maneuver"] };
  const EDGE_LABELS = { "context|hyper": "Hyper Agent to Context", "context|snapshot": "Context to Snapshot", "fsm|snapshot": "Snapshot to FSM Runner", "fsm|maneuver": "FSM Runner to Maneuver", "hyper|maneuver": "Hyper Agent to Maneuver", "hyper|skills": "Hyper Agent to Skills", "command|maneuver": "Maneuver to Command", "command|feedback": "Command to Feedback", "feedback|maneuver": "Feedback to Maneuver" };
  const state = { active: false, available: false, missions: [], missionId: "", items: [], cursor: 0, playing: true, speed: 1, timer: null, pollTimer: null, requestToken: 0, debugToken: 0, selectionId: "", correlationId: "", view: "overview", debug: { enabled: false, profiles: [], invocations: [] }, invocationId: "" };
  const $ = (id) => document.getElementById(id);
  const els = {
    runtime: $("runtimeState"), runtimeLabel: $("runtimeLabel"), session: $("sessionMeta"), picker: $("missionPicker"), mission: $("missionSelect"), count: $("observationCount"), graph: $("graphStage"), idle: $("idleNote"), mobileFlow: $("mobileFlow"), summaries: $("summaries"), summaryStatus: $("summaryStatus"), summaryLatest: $("summaryLatest"), summaryHistory: $("summaryHistory"), replay: $("replayControls"), scrubber: $("scrubber"), end: $("scrubberEnd"), play: $("playPause"), speed: $("speed"), events: $("eventList"), trace: $("traceStrip"), title: $("viewTitle"), inspectorKicker: $("inspectorKicker"), inspectorTitle: $("inspectorTitle"), inspectorCopy: $("inspectorCopy"), details: $("detailList"), safety: $("safetyList"), clear: $("clearSelection"), debugProfiles: $("debugProfiles"), debugStatus: $("debugStatus"), debugEmpty: $("debugEmpty"), debugProfileList: $("debugProfileList"), debugTimeline: $("debugTimeline"), debugEvents: $("debugEventList")
  };

  function text(value, fallback, limit) { return typeof value === "string" && value.trim() ? value.trim().slice(0, limit || 240) : fallback; }
  function list(value) { return Array.isArray(value) ? value.filter((item) => typeof item === "string").map((item) => item.slice(0, 80)).slice(0, 12) : []; }
  function has(value, key) { return Object.prototype.hasOwnProperty.call(value, key); }
  function safePayload(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return []; return Object.entries(value).filter(([key, item]) => SAFE_PAYLOAD_FIELDS.has(key) && (typeof item === "string" || typeof item === "number" || typeof item === "boolean")).slice(0, 6).map(([key, item]) => [String(key).slice(0, 48), String(item).slice(0, 120)]); }
  function summaryData(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const summary = text(value.summary, "", 480); if (!summary) return null; const start = typeof value.input_start_sequence === "number" || typeof value.input_start_sequence === "string" ? String(value.input_start_sequence).slice(0, 40) : ""; const end = typeof value.input_end_sequence === "number" || typeof value.input_end_sequence === "string" ? String(value.input_end_sequence).slice(0, 40) : ""; const prior = Array.isArray(value.prior_summary_ids) ? value.prior_summary_ids.filter((item) => typeof item === "string").slice(0, 8).map((item) => item.slice(0, 80)) : []; return { summary, start, end, prior }; }
  function normalize(raw, index) { if (!raw || typeof raw !== "object") return null; const item = {}; Object.keys(raw).forEach((key) => { if (SAFE_FIELDS.has(key)) item[key] = raw[key]; }); const eventId = text(item.event_id, "", 160), traceId = text(item.trace_id, eventId || "", 160); if (!eventId && !traceId) return null; return { key: traceId || eventId, missionId: text(item.mission_id, "unknown", 160), traceId, eventId, component: text(item.component, "runtime", 100).toLowerCase(), authority: text(item.authority, "unavailable", 100), kind: text(item.event_kind, "observation", 120), occurred: text(item.occurred_at, "time unavailable", 160), sequence: Number.isFinite(item.observation_sequence) ? item.observation_sequence : index + 1, status: text(item.status, "", 80), outcome: text(item.outcome, "", 80), correlationId: text(item.correlation_id, "", 160), parentId: text(item.parent_id, "", 160), replay: text(item.replay_disposition, "normal", 80), payload: safePayload(item.payload), summary: summaryData(item.payload), redacted: list(item.redacted_fields), missing: list(item.missing_fields) }; }
  function normalizeProfile(raw) { if (!raw || typeof raw !== "object") return null; const skills = Array.isArray(raw.skills) ? raw.skills.map((skill) => skill && typeof skill === "object" ? { name: text(skill.name, "Unnamed skill", 120), version: text(skill.version, "", 80), path: text(skill.path, "", 240) } : null).filter(Boolean).slice(0, 24) : []; const tools = Array.isArray(raw.tools) ? raw.tools.map((tool) => typeof tool === "string" ? text(tool, "", 160) : tool && typeof tool === "object" ? text(tool.name, readableValue(tool).slice(0, 240), 240) : "").filter(Boolean).slice(0, 32) : []; return { role: text(raw.agent_role, "Unassigned role", 120), skills, tools }; }
  function normalizeInvocation(raw, index) { if (!raw || typeof raw !== "object") return null; const kind = text(raw.kind, "agent", 32).toLowerCase(); const safeKind = ["agent", "llm", "tool"].includes(kind) ? kind : "agent"; return { id: text(raw.invocation_id, "", 160) || "invocation-" + String(index + 1), sequence: Number.isFinite(raw.sequence) ? raw.sequence : index + 1, role: text(raw.agent_role, "Unassigned role", 120), kind: safeKind, name: text(raw.name, safeKind === "llm" ? "Language model" : safeKind === "tool" ? "Tool call" : "Agent step", 160), startedAt: text(raw.started_at, "Time unavailable", 160), finishedAt: text(raw.finished_at, "", 160), parentId: text(raw.parent_id, "", 160), hasInput: has(raw, "input"), input: raw.input, hasOutput: has(raw, "output"), output: raw.output, hasError: has(raw, "error"), error: raw.error }; }
  function componentFor(item) { const name = item.component.replace(/[_ ]/g, "-"); if (name.includes("mission-log-summarizer") || name.includes("summarizer")) return "summary"; if (name.includes("hyper")) return "hyper-agent"; if (name.includes("maneuver") || name.includes("control")) return "maneuver-control"; if (name.includes("context")) return "context"; if (name.includes("fsm") || name.includes("runner")) return "fsm"; if (name.includes("snapshot") || name.includes("state")) return "snapshot"; if (name.includes("skill") || name.includes("advisor")) return "skills"; if (name.includes("feedback") || name.includes("environment")) return "feedback"; return "command"; }
  function edgeKey(first, second) { const names = { "hyper-agent": "hyper", "maneuver-control": "maneuver" }; return [names[first] || first, names[second] || second].sort().join("|"); }
  function edgesFor(item, items) { const parent = items.find((candidate) => candidate.eventId === item.parentId || candidate.traceId === item.parentId); const edge = parent ? edgeKey(componentFor(parent), componentFor(item)) : ""; return edge && EDGE_LABELS[edge] ? [edge] : (DEFAULT_EDGES[componentFor(item)] || []); }
  function selectedItem() { return state.items.find((item) => item.key === state.selectionId) || null; }
  function selectedInvocation() { return state.debug.invocations.find((item) => item.id === state.invocationId) || null; }
  function matchesView(item) { const components = VIEWS[state.view].components; return !components || components.includes(componentFor(item)); }
  function related(item, selected) { return selected && (item.key === selected.key || (selected.correlationId && item.correlationId === selected.correlationId) || (selected.eventId && item.parentId === selected.eventId) || (selected.traceId && item.parentId === selected.traceId) || (item.eventId && selected.parentId === item.eventId) || (item.traceId && selected.parentId === item.traceId)); }
  function derive() { const cursor = Math.max(0, Math.min(state.cursor, Math.max(state.items.length - 1, 0))); const live = state.available ? state.items.slice(0, cursor + 1) : []; const viewItems = live.filter(matchesView); let selected = selectedItem(); if (selected && (!live.some((item) => item.key === selected.key) || !matchesView(selected))) selected = null; return { cursor, live, viewItems, selected, correlated: selected && state.correlationId ? viewItems.filter((item) => related(item, selected)) : [], totalInView: state.items.filter(matchesView).length }; }
  function clearTimer() { if (state.timer) { window.clearInterval(state.timer); state.timer = null; } }
  function clearPollTimer() { if (state.pollTimer) { window.clearTimeout(state.pollTimer); state.pollTimer = null; } }
  function resetTimer() { clearTimer(); if (state.available && state.playing) state.timer = window.setInterval(() => { if (state.items.length < 2) return; state.cursor = state.cursor >= state.items.length - 1 ? 0 : state.cursor + 1; renderAll(); }, 1000 / state.speed); }
  function resetPollTimer() { clearPollTimer(); if (state.active) state.pollTimer = window.setTimeout(poll, POLL_MS); }
  function resetMission(nextMission) { state.requestToken += 1; state.debugToken += 1; state.missionId = nextMission; state.items = []; state.cursor = 0; state.selectionId = ""; state.correlationId = ""; state.invocationId = ""; state.debug = { enabled: false, profiles: [], invocations: [] }; state.playing = true; clearTimer(); }
  function renderMissionPicker() { els.picker.hidden = !state.available || !state.missions.length; els.mission.replaceChildren(); state.missions.forEach((id) => { const option = document.createElement("option"); option.value = id; option.textContent = id.slice(0, 80); option.selected = id === state.missionId; els.mission.append(option); }); }
  function renderStatus(runtime, unavailable) { const legacyAvailable = runtime && !has(runtime, "available") && Boolean(runtime.active); state.available = Boolean(runtime && (runtime.available || legacyAvailable)) && !unavailable; state.active = state.available && Boolean(runtime && runtime.active); els.runtime.className = "runtime-state" + (unavailable ? " unavailable" : state.active ? " live" : ""); els.runtimeLabel.textContent = unavailable ? "Runtime unavailable" : state.active ? "Runtime active" : state.available ? "Runtime available" : "Runtime idle"; if (state.available && Array.isArray(runtime.mission_ids)) state.missions = runtime.mission_ids.filter((id) => typeof id === "string" && id.trim()).map((id) => id.slice(0, 160)); if (state.available && !state.missionId && state.missions.length) resetMission(state.missions[0]); els.session.textContent = state.available && state.missionId ? "Mission " + state.missionId.slice(0, 32) : ""; els.graph.classList.toggle("live", state.active); els.idle.hidden = state.available; els.replay.hidden = !state.available; els.trace.hidden = !state.available || state.view === "debug"; renderMissionPicker(); }
  function addDetailTo(target, label, value, multiline) { const row = document.createElement("div"), dt = document.createElement("dt"), dd = document.createElement("dd"); dt.textContent = label; if (multiline) String(value).split("\n").forEach((line, index) => { if (index) dd.append(document.createElement("br")); dd.append(document.createTextNode(line)); }); else dd.textContent = value; row.append(dt, dd); target.append(row); }
  function addDetail(label, value, multiline) { addDetailTo(els.details, label, value, multiline); }
  function renderGraph(model) { document.querySelectorAll(".node").forEach((node) => node.classList.remove("focused", "view-muted", "view-focus")); document.querySelectorAll(".edge").forEach((edge) => edge.classList.remove("active-flow", "related")); els.mobileFlow.replaceChildren(); if (!state.available) { els.count.textContent = "Architecture ready"; return; } if (state.view === "debug") { els.count.textContent = state.debug.enabled ? state.debug.invocations.length + " invocations" : "Debug unavailable"; return; } els.count.textContent = state.view === "overview" ? state.items.length + " observed" : model.totalInView + " in view / " + state.items.length + " observed"; const scope = VIEWS[state.view].components; if (scope) document.querySelectorAll(".node").forEach((node) => node.classList.add(scope.includes(node.dataset.component) ? "view-focus" : "view-muted")); const edgeIds = new Set(); model.viewItems.forEach((item) => { const node = document.querySelector('[data-component="' + componentFor(item) + '"]'); if (node) node.classList.add("focused"); edgesFor(item, model.live).forEach((id) => edgeIds.add(id)); }); edgeIds.forEach((id) => { const edge = document.querySelector('[data-edge="' + id + '"]'); if (edge) edge.classList.add("active-flow"); const chip = document.createElement("span"); chip.className = "flow-chip active-flow"; chip.textContent = EDGE_LABELS[id]; els.mobileFlow.append(chip); }); model.correlated.forEach((item) => edgesFor(item, model.live).forEach((id) => { const edge = document.querySelector('[data-edge="' + id + '"]'); if (edge) edge.classList.add("related"); })); }
  function summaryMeta(item) { const parts = []; if (item.summary.start || item.summary.end) parts.push("Input " + (item.summary.start || "?") + " to " + (item.summary.end || "?")); if (item.summary.prior.length) parts.push("Prior: " + item.summary.prior.slice(0, 4).map((id) => id.slice(0, 32)).join(", ")); return parts.join(" · "); }
  function renderSummaries(model) { const summaries = state.available && state.view === "overview" ? model.live.filter((item) => componentFor(item) === "summary" && item.summary) : []; els.summaries.hidden = !state.available || state.view !== "overview"; els.summaryLatest.replaceChildren(); els.summaryHistory.replaceChildren(); if (els.summaries.hidden) return; if (!summaries.length) { els.summaryStatus.textContent = "Unavailable"; els.summaryLatest.textContent = "No public summary has been observed for this mission."; return; } const latest = summaries[summaries.length - 1]; els.summaryStatus.textContent = summaries.length + " observed"; const body = document.createElement("p"), meta = document.createElement("p"); body.textContent = latest.summary.summary; meta.className = "summary-meta"; meta.textContent = summaryMeta(latest); els.summaryLatest.append(body, meta); summaries.slice(0, -1).reverse().slice(0, 8).forEach((item) => { const button = document.createElement("button"); button.type = "button"; button.className = "summary-item" + (model.selected && model.selected.key === item.key ? " selected" : ""); button.dataset.key = item.key; button.title = "Select prior summary"; button.textContent = "OBS " + item.sequence + (summaryMeta(item) ? " · " + summaryMeta(item) : ""); els.summaryHistory.append(button); }); }
  function renderEvents(model) { els.events.replaceChildren(); if (!state.available || state.view === "debug") return; const fragment = document.createDocumentFragment(); model.viewItems.forEach((item) => { const button = document.createElement("button"), seq = document.createElement("span"), kind = document.createElement("strong"), meta = document.createElement("small"); button.type = "button"; button.className = "event" + (model.selected && item.key === model.selected.key ? " selected" : "") + (model.correlated.some((entry) => entry.key === item.key) ? " related" : ""); button.dataset.key = item.key; button.setAttribute("aria-label", "Select observed event " + item.sequence + ": " + item.kind); seq.className = "sequence"; seq.textContent = "OBS " + item.sequence; kind.textContent = item.kind; meta.textContent = componentFor(item) + (item.status ? " / " + item.status : item.outcome ? " / " + item.outcome : ""); button.append(seq, kind, meta); fragment.append(button); }); els.events.append(fragment); }
  function readableValue(value) { if (typeof value === "string") return value.slice(0, 12000); try { return JSON.stringify(value, null, 2).slice(0, 12000); } catch (_) { return String(value).slice(0, 12000); } }
  function renderDebug(model) { const visible = state.view === "debug" && state.available; els.debugProfiles.hidden = !visible; els.debugTimeline.hidden = !visible || !state.debug.enabled; els.debugProfileList.replaceChildren(); els.debugEvents.replaceChildren(); els.debugEmpty.textContent = ""; if (!visible) return; if (!state.debug.enabled) { els.debugStatus.textContent = "Unavailable"; els.debugEmpty.textContent = "Debug activity is not enabled for this mission."; return; } els.debugStatus.textContent = state.debug.profiles.length + " roles / " + state.debug.invocations.length + " invocations"; if (!state.debug.profiles.length) els.debugEmpty.textContent = "No agent capabilities were reported for this mission."; state.debug.profiles.forEach((profile) => { const skills = profile.skills.map((skill) => skill.name + (skill.version ? " " + skill.version : "") + (skill.path ? " (" + skill.path + ")" : "")).join(", ") || "None reported"; const tools = profile.tools.join(", ") || "None reported"; addDetailTo(els.debugProfileList, profile.role, "Skills: " + skills + "  |  Tools: " + tools); }); const fragment = document.createDocumentFragment(); state.debug.invocations.forEach((invocation) => { const button = document.createElement("button"), seq = document.createElement("span"), name = document.createElement("strong"), meta = document.createElement("small"); button.type = "button"; button.className = "event" + (invocation.id === state.invocationId ? " selected" : ""); button.dataset.invocation = invocation.id; button.setAttribute("aria-label", "Inspect invocation " + invocation.sequence + ": " + invocation.name); seq.className = "sequence"; seq.textContent = "STEP " + invocation.sequence; name.textContent = invocation.name; meta.textContent = invocation.role + " / " + invocation.kind + (invocation.parentId ? " / parent " + invocation.parentId : "") + (invocation.hasError ? " / error" : ""); button.append(seq, name, meta); fragment.append(button); }); els.debugEvents.append(fragment); }
  function renderInspector(model) { els.details.replaceChildren(); els.safety.replaceChildren(); if (state.view === "debug") { const invocation = selectedInvocation(); els.inspectorKicker.textContent = "Invocation inspector"; if (!state.available) { els.inspectorTitle.textContent = "Agent activity"; els.inspectorCopy.textContent = "Select an available mission to inspect agent activity."; return; } if (!state.debug.enabled) { els.inspectorTitle.textContent = "Debug unavailable"; els.inspectorCopy.textContent = "This mission does not expose debug activity."; return; } if (!invocation) { els.inspectorTitle.textContent = "No invocation selected"; els.inspectorCopy.textContent = "Select an invocation to inspect its exchanged data."; return; } els.inspectorTitle.textContent = invocation.name; els.inspectorCopy.textContent = invocation.role + " recorded a " + invocation.kind + " invocation."; [["Sequence", invocation.sequence], ["Role", invocation.role], ["Kind", invocation.kind], ["Invocation ID", invocation.id], ["Parent ID", invocation.parentId || "not reported"], ["Started", invocation.startedAt], ["Finished", invocation.finishedAt || "not reported"]].forEach(([label, value]) => addDetail(label, String(value))); if (invocation.hasInput) addDetail("Input", readableValue(invocation.input), true); if (invocation.hasOutput) addDetail("Output", readableValue(invocation.output), true); if (invocation.hasError) addDetail("Error", readableValue(invocation.error), true); return; } const item = model.selected; if (!state.available || !item) { const view = VIEWS[state.view]; els.inspectorKicker.textContent = state.available ? view.title : "Selected event"; els.inspectorTitle.textContent = state.available ? view.title : "No observation selected"; els.inspectorCopy.textContent = state.available ? view.detail : "Trace details appear when an available run has an observed event selected."; return; } els.inspectorKicker.textContent = "Observed event " + item.sequence; els.inspectorTitle.textContent = item.kind; els.inspectorCopy.textContent = componentFor(item) + " reported this observation."; [["Mission", item.missionId], ["Event ID", item.eventId || "not reported"], ["Trace ID", item.traceId || "not reported"], ["Parent ID", item.parentId || "not reported"], ["Correlation", item.correlationId || "not reported"], ["Authority", item.authority], ["Status", item.status || item.outcome || "not reported"], ["Replay", item.replay]].forEach(([label, value]) => addDetail(label, value)); item.payload.forEach(([key, value]) => addDetail(key, value)); const notes = []; if (item.redacted.length) notes.push(["Redacted: " + item.redacted.join(", "), ""]); if (item.missing.length) notes.push(["Missing: " + item.missing.join(", "), "red"]); if (!notes.length) notes.push(["Public fields only", ""]); notes.forEach(([value, cls]) => { const note = document.createElement("p"); note.className = "safety-note " + cls; note.textContent = value; els.safety.append(note); }); }
  function renderReplay(model) { els.scrubber.max = Math.max(state.items.length - 1, 0); els.scrubber.value = model.cursor; els.end.textContent = state.items.length + " observed"; els.play.textContent = state.playing ? "Pause" : "Play"; els.play.setAttribute("aria-label", state.playing ? "Pause replay" : "Play replay"); els.clear.hidden = !state.correlationId; }
  function renderAll() { const model = derive(); state.cursor = model.cursor; renderGraph(model); renderSummaries(model); renderEvents(model); renderDebug(model); renderInspector(model); renderReplay(model); }
  async function loadTrace() { const missionId = state.missionId, token = ++state.requestToken; if (!missionId) { state.items = []; return false; } const response = await fetch("/api/trace?mission_id=" + encodeURIComponent(missionId), { headers: { Accept: "application/json" }, cache: "no-store" }); if (!response.ok) throw new Error("trace unavailable"); const trace = await response.json(); if (token !== state.requestToken || missionId !== state.missionId || !state.available) return false; state.items = Array.isArray(trace.items) ? trace.items.map(normalize).filter((item) => item && item.missionId === missionId) : []; state.cursor = Math.min(state.cursor, Math.max(state.items.length - 1, 0)); return true; }
  async function loadDebug() { const missionId = state.missionId, token = ++state.debugToken; if (!missionId) return false; try { const response = await fetch("/api/debug?mission_id=" + encodeURIComponent(missionId), { headers: { Accept: "application/json" }, cache: "no-store" }); if (!response.ok) throw new Error("debug unavailable"); const debug = await response.json(); if (token !== state.debugToken || missionId !== state.missionId || !state.available) return false; state.debug = { enabled: Boolean(debug && debug.enabled), profiles: Array.isArray(debug && debug.profiles) ? debug.profiles.map(normalizeProfile).filter(Boolean) : [], invocations: Array.isArray(debug && debug.invocations) ? debug.invocations.map(normalizeInvocation).filter(Boolean).sort((first, second) => first.sequence - second.sequence) : [] }; if (!state.debug.invocations.some((item) => item.id === state.invocationId)) state.invocationId = ""; return true; } catch (_) { if (token === state.debugToken && missionId === state.missionId) { state.debug = { enabled: false, profiles: [], invocations: [] }; state.invocationId = ""; } return false; } }
  async function refreshMission() { if (!state.available) return; try { await Promise.all([loadTrace(), loadDebug()]); } catch (_) { state.items = []; } renderAll(); resetTimer(); }
  async function poll() { clearPollTimer(); try { const response = await fetch("/api/runtime", { headers: { Accept: "application/json" }, cache: "no-store" }); if (!response.ok) throw new Error("runtime unavailable"); renderStatus(await response.json(), false); await refreshMission(); } catch (_) { renderStatus(null, true); renderAll(); clearTimer(); } resetPollTimer(); }
  document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { state.view = tab.dataset.view; const selected = selectedItem(); if (state.view !== "debug" && selected && !matchesView(selected)) { state.selectionId = ""; state.correlationId = ""; } document.querySelectorAll(".tab").forEach((button) => { const active = button === tab; button.classList.toggle("active", active); button.setAttribute("aria-selected", String(active)); }); els.title.textContent = VIEWS[state.view].title; els.trace.hidden = !state.available || state.view === "debug"; renderAll(); }));
  els.mission.addEventListener("change", () => { if (state.missions.includes(els.mission.value)) { resetMission(els.mission.value); renderMissionPicker(); renderAll(); refreshMission(); } });
  $("playPause").addEventListener("click", () => { state.playing = !state.playing; renderAll(); resetTimer(); }); $("restart").addEventListener("click", () => { state.cursor = 0; state.playing = true; renderAll(); resetTimer(); }); els.speed.addEventListener("change", () => { state.speed = Number(els.speed.value); resetTimer(); }); els.scrubber.addEventListener("input", () => { state.cursor = Number(els.scrubber.value); state.playing = false; renderAll(); resetTimer(); });
  els.events.addEventListener("click", (event) => { const target = event.target.closest(".event"), item = target && state.items.find((entry) => entry.key === target.dataset.key); if (!item) return; state.selectionId = item.key; state.correlationId = item.correlationId || item.eventId || item.traceId; state.cursor = Math.max(state.cursor, state.items.findIndex((entry) => entry.key === item.key)); renderAll(); }); els.debugEvents.addEventListener("click", (event) => { const target = event.target.closest(".event"); if (target && state.debug.invocations.some((item) => item.id === target.dataset.invocation)) { state.invocationId = target.dataset.invocation; renderAll(); } }); els.clear.addEventListener("click", () => { state.correlationId = ""; renderAll(); }); els.summaryHistory.addEventListener("click", (event) => { const target = event.target.closest(".summary-item"), item = target && state.items.find((entry) => entry.key === target.dataset.key); if (!item) return; state.selectionId = item.key; state.correlationId = item.correlationId || item.eventId || item.traceId; state.cursor = Math.max(state.cursor, state.items.findIndex((entry) => entry.key === item.key)); renderAll(); }); document.querySelectorAll(".node").forEach((node) => node.addEventListener("click", () => { const item = derive().viewItems.find((entry) => componentFor(entry) === node.dataset.component); if (!item) return; state.selectionId = item.key; state.correlationId = item.correlationId || item.eventId || item.traceId; state.cursor = Math.max(state.cursor, state.items.findIndex((entry) => entry.key === item.key)); renderAll(); }));
  renderAll(); poll();
}());
